name: test

on:
  push:

jobs:
  show-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          echo "Before commit: ${{ github.event.before }}"
          echo "After  commit: ${{ github.sha }}"
          echo

          echo "Changed files between before and after:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tee changed_files.txt

          echo
          echo "==== changed_files.txt 내용 ===="
          cat changed_files.txt || echo "(no changed files)"
